#!/usr/bin/python2.7 -O

"""
Littlewing: Simple, powerful infrastructure automation.
https://github.com/kfeldmann/littlewing

Copyright (c) 2016, Kris Feldmann
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

  1. Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above
     copyright notice, this list of conditions and the following
     disclaimer in the documentation and/or other materials provided
     with the distribution.

  3. Neither the name of the copyright holder nor the names of its
     contributors may be used to endorse or promote products derived
     from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER
OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import sys
import yaml
import json
import os
import re
import subprocess
from urllib import quote, unquote
import time

AWSCLI = os.environ.get('AWSCLI', 'aws')
filename = '(none)'
lineno = '(none)'
stepno = '(none)'
ts = time.strftime('%Y%m%d%H%M%S', time.localtime())

def _err(message):
    """
    Write error message to stderr along with filename,
    stepno, and lineno, and then exit(1).
    """
    sys.stderr.write('ERROR: file: %s, step: %s, line: %s\n' \
                    % (filename, stepno, lineno))
    sys.stderr.write('ERROR: %s\n' % message)
    raise SystemExit(1)

def _wrn(message):
    """
    Write warning message to stderr along with filename,
    stepno, and lineno.
    """
    sys.stderr.write('WARN: file: %s, step: %s, line: %s\n' \
                    % (filename, stepno, lineno))
    sys.stderr.write('WARN: %s\n' % message)
    return None

def _inf(message):
    "Write informational message to stdout."
    sys.stdout.write('INFO: %s\n' % message)
    return None

def _dbg(message):
    """
    If the environment variable DEBUG has been set, write
    debugging message to stdout.
    """
    if os.environ.get('DEBUG', False):
        sys.stdout.write('DEBUG: %s\n' % message)
    return None

def usage():
    "Write usage statement to stderr and exit(2)."
    sys.stderr.write('Usage: lw [-l|--list|<target>]\n')
    raise SystemExit(2)

def __varsub(in_str):
    "Dereference variables and output references."
    global filename, lineno
    _dbg('__varsub(): starting with in_str = %s' % in_str)
    words = in_str.split('.')
    _dbg('__varsub(): words = %s' % repr(words))
    if words[0] == 'var':
        if len(words) == 2:
            if words[1] in var:
                return var[words[1]]
            else:
                raise ValueError('Unknown variable: %s' % words[1])
        elif len(words) == 3:
            if words[1] in var:
                if isinstance(var[words[1]], dict) and words[2] in var[words[1]]:
                    return var[words[1]][words[2]]
                elif isinstance(var[words[1]], basestring):
                    raise ValueError('Treating a string variable as a map: %s.%s'
                                    % (words[1], words[2]))
                else:
                    raise ValueError('Unknown variable: %s.%s'
                                    % (words[1], words[2]))
            else:
                raise ValueError('Unknown variable: %s.%s'
                                % (words[1], words[2]))
    if words[0] == 'aws':
        fname = '.'.join(words[:4])
    elif words[0] == 'exec':
        fname = '.'.join(words[:3])
    else:
        _err('Unknown provider: %s' % words[0])
    try:
        f = open('%s/%s' % (outdir, fname), 'r')
        filename = '%s/%s' % (outdir, fname)
    except IOError:
        _err('Unknown resource: %s' % fname)
    lineno = 0
    while True:
        line = f.readline()
        lineno += 1
        if line == '':
            break
        line = line.strip()
        try:
            n, v = line.split(':', 1)
        except ValueError:
            f.close()
            _err('Malformed line in output file (%s): %s'
                % (fname, line))
        if n == in_str:
            f.close()
            return unquote(v)
    f.close()
    _err('Unknown resource attribute: %s' % in_str)

def varsub(val):
    """
    Recursively (to a limit) find variables in the input string
    and call __varsub() to dereference them.
    """
    _dbg('varsub(): starting with val = %s' % val)
    if isinstance(val, None.__class__):
        return val
    if isinstance(val, int):
        return str(val)
    i = 0
    while i < 10:
        if marker == 'dollar':
            s = re.search(r'\$\{([^${}]+)\}', val)
        else:
            s = re.search(r'\~\{([^~{}]+)\}', val)
        try:
            s.group(1)
        except (IndexError, AttributeError):
            break
        _dbg('varsub(): s.group(0) = %s' % s.group(0))
        _dbg('varsub(): s.group(1) = %s' % s.group(1))
        needle = s.group(0).replace('$', r'\$')
        val = re.sub(needle, __varsub(s.group(1)), val)
        i += 1
    if marker == 'dollar':
        # Un-escape $\\{ --> ${, and $\\\{ --> $\{
        val = val.replace(r'$\\{', r'${')
        val = val.replace(r'$\\\{', r'$\{')
    return val

def aws_call(region, profile, cmdtuple, argtuple):
    "Spawn aws-cli subprocess to execute commands."
    if (not region) or (not profile):
        _err('Must set region and profile before calling aws.')
    args = [
            AWSCLI,
            '--region', region,
            '--profile', profile
           ]
    args.extend(cmdtuple)
    if argtuple:
        args.extend(argtuple)
    try:
        outdata = subprocess.check_output(args)
    except Exception as ex:
        _err('Failed to run %s %s %s: %s\n' \
             % (AWSCLI, cmdtuple[0], cmdtuple[1], ex) \
             + 'ERROR: Args: %s' % repr(args))
    if outdata: # Some calls do not return data
        try:
            outdict = json.loads(outdata)
        except Exception as ex:
            _err( \
            """Failed to parse json response from %s %s %s.
            Exception is: %s
            JSON source:
            %s
            """ % (AWSCLI, cmdtuple[0], cmdtuple[1], ex, outdata))
        outdict['Output'] = outdata
    else:
        outdict = None
    return outdict

def exec_call(cmd, argtuple):
    "Spawn subprocess to execute <cmd>."
    args = [cmd]
    if argtuple:
        args.extend(argtuple)
    try:
        outdata = subprocess.check_output(args)
    except Exception as ex:
        _err('Failed to run %s: %s' % (cmd, ex))
    return {'Output': outdata}

def stringify(path, name, obj):
    """
    Recursively convert heirarchical object into a list of strings,
    each using a dotted notation to represent the branch to each
    attribute and its value.
    """
    strings = []
    if obj == None:
        return strings
    if isinstance(obj, dict):
        for k in obj.keys():
            strings.extend(stringify('%s.%s' % (path, name), k, obj[k]))
    elif isinstance(obj, list):
        i = 0
        for item in obj:
            strings.extend(stringify('%s.%s' % (path, name), i, item))
            i += 1
        this = '%s.%s.Count:%d' % (path, name, len(obj))
        strings.append(this.lstrip('.'))
    else:
        this = '%s.%s:%s' % (path, name, quote(str(obj)))
        strings.append(this.lstrip('.'))
    return strings

def store_output(name, outdict):
    "Stringify and write out the output data from a step."
    try:
        f = open('%s/%s' % (outdir, name), 'w')
    except IOError:
        _err('Failed to open output file: %s' % name)
    for line in stringify('', name, outdict):
        f.write('%s\n' % line)
    f.close()
    return None

def clear_all_output():
    "Move all output aside, effectively clearing it."
    global ts
    if not os.path.exists('%s-cleared-%s' % (outdir, ts)):
        os.mkdir('%s-cleared-%s' % (outdir, ts))
    for f in os.listdir(outdir):
        os.rename( \
          '%s/%s' % (outdir, f),
          '%s-cleared-%s/%s' % (outdir, ts, f))
    return None

def clear_one_output(path):
    "Move one output file aside, effectively clearing it."
    global ts
    if not os.path.exists('%s/%s' \
                      % (outdir, path)):
        _err("Output not found: %s. Was it already cleared?" % path)
    else:
        if not os.path.exists('%s-cleared-%s' % (outdir, ts)):
            os.mkdir('%s-cleared-%s' % (outdir, ts))
        os.rename( \
          '%s/%s' % (outdir, path),
          '%s-cleared-%s/%s' % (outdir, ts, path))
    return None

def varsub_tuple(intuple):
    "Substitute variables in each element of a tuple."
    if intuple == None:
        return None
    outtuple = []
    for item in intuple:
        try:
            outtuple.append(varsub(item))
        except ValueError as ex:
            _err(str(ex))
    return outtuple

def set_region(value, tries=1, trylimit=1):
    """
    Set the global 'region` and var['REGION'] variables
    using variable substitution.
    """
    global region
    try:
        region = varsub(value)
        var['REGION'] = region
    except ValueError as ex:
        if tries >= trylimit:
            _err(str(ex))
        else:
            return False
    return True

def set_profile(value, tries=1, trylimit=1):
    """
    Set the global 'profile` and var['PROFILE'] variables
    using variable substitution.
    """
    global profile
    try:
        profile = varsub(value)
        var['PROFILE'] = profile
    except ValueError as ex:
        if tries >= trylimit:
            _err(str(ex))
        else:
            return False
    return True

def start_loop(this_stepno, value, tries=1, trylimit=1):
    """
    Push the start and count of this loop onto the loop_stack.
    Use variable substitution for the length.
    The values in loop_stack[] have the following format:
    [starting_stepno, loop_count, loop_index]
    The loop_index value is incremented during the loop
    execution until it is equal to loop_count.
    """
    try:
        count = varsub(value)
    except ValueError as ex:
        if tries >= trylimit:
            _err(str(ex))
        else:
            return False
    else:
        try:
            count = int(count)
        except ValueError as ex:
            _err(str(ex))
        else:
            _dbg('Pushing loop onto the stack: [%d, %d, 0]' \
                % (this_stepno, count))
            loop_stack.append([this_stepno, count, 0])
    set_loop_index_var()
    return True

def check_null_loop():
    """
    Are we inside a loop that is already at it's limit? For example,
    a zero-length loop which can be used as a poor-man's boolean.
    """
    if len(loop_stack) > 0:
        if loop_stack[-1][2] >= loop_stack[-1][1]:
            _dbg('check_null_loop() returning True')
            return True
    else:
        _dbg('check_null_loop() returning False')
        return False

def add_null_loop():
    global null_loop_depth
    null_loop_depth += 1
    _dbg('Added a null loop')
    return None

def end_null_loop():
    global null_loop_depth
    if null_loop_depth <= 0:
        return False
    null_loop_depth -= 1
    _dbg('Subtracted a null loop')
    return True

def increment_loop_index():
    """
    Increment the loop_index value.
    Return True if the loop should continue, and False if it has reached
    the end (index == count).
    """
    loop_stack[-1][2] += 1
    _dbg('Loop status: %d, %d, %d' \
        % (loop_stack[-1][0], loop_stack[-1][1], loop_stack[-1][2]))
    if loop_stack[-1][2] >= loop_stack[-1][1]:
        _dbg('Loop done. Popping from loop_stack.')
        loop_stack.pop()
        set_loop_index_var()
        return False
    else:
        _dbg('Loop continuing.')
        set_loop_index_var()
        return True

def set_loop_index_var():
    if len(loop_stack) > 0:
        var['LOOP_INDEX'] = str(loop_stack[-1][2])
        _dbg('Setting LOOP_INDEX to %s' % str(loop_stack[-1][2]))
        if len(loop_stack) > 1:
            j = 1
            for i in range(len(loop_stack)-2, -1, -1):
                var['LOOP_INDEX_%d' % j] = str(loop_stack[i][2])
                _dbg('i=%d, Setting LOOP_INDEX_%d to %s' % (i, j, str(loop_stack[i][2])))
                j += 1
    else:
        var['LOOP_INDEX'] = "0"
    return None

def set_var(name, value, tries=1, trylimit=1):
    "Set global 'var[name]' using variable substitution."
    if isinstance(value, basestring):
        try:
            var[name] = varsub(value)
            _dbg('Set string var[%s] = "%s"' % (name, var[name]))
        except ValueError as ex:
            if tries >= trylimit:
                _err(str(ex))
            else:
                return False
    elif isinstance(value, int):
        var[name] = str(value)
        _dbg('Set int var[%s] = "%s"' % (name, var[name]))
    elif isinstance(value, dict):
        var[name] = value
        _dbg('Set dict var[%s] = "%s"' % (name, repr(var[name])))
    else:
        _err('Unknown variable type for var.%s' % name)
    return True

def set_default_target(value, tries=1, trylimit=1):
    """
    Set global 'target' (once) using variable substitution.
    """
    global target
    global default_found

    if not target:
        if isinstance(value, basestring):
            try:
                target = varsub(value)
                if listing:
                    default_found = True
            except ValueError as ex:
                if tries >= trylimit:
                    _err(str(ex))
                else:
                    return False
        else:
            _wrn('Default target must be a string.')
        return True

def set_target_groups(tgdict, tries=1, trylimit=1):
    "Set global 'target_groups' using variable substitution."
    if not isinstance(tgdict, dict):
        _wrn("'target-groups' must be a dict.")
        return True
    for tgname in tgdict.keys():
        if not isinstance(tgdict[tgname], list):
            _wrn("'target-groups: %s' must be a list." % tgname)
            return True
        try:
            tgn = varsub(tgname)
        except ValueError as ex:
            if tries >= trylimit:
                _err(str(ex))
            else:
                return False
        else:
            try:
                target_groups[tgn] = varsub_tuple(tgdict[tgname])
            except ValueError as ex:
                if tries >= trylimit:
                    _err(str(ex))
                else:
                    return False
    return True

### main ###############################################################

if len(sys.argv) > 2 \
        or  '-?' in sys.argv \
        or '-h' in sys.argv \
        or '--help' in sys.argv:
    usage()

listing = False
target = None
default_found = False
outdir = '.lw-output'

if len(sys.argv) == 2:
    if sys.argv[1] in ('-l', '--list'):
        listing = True
    else:
        target = sys.argv[1]

# Legacy support
if os.path.exists('.terraflop-output'):
    outdir = '.terraflop-output'

if not os.path.exists(outdir):
    os.mkdir(outdir)

all_files = os.listdir('.')
input_files = []
for f in all_files:
    if f[-4:] == '.yml':
        input_files.append(f)
input_files.sort()

region = None
profile = None
var = {}
var['USER'] = os.environ.get('USER', 'littlewing')
var['LOOP_INDEX'] = "0"
var['LOOP_INDEX_1'] = "0"
var['LOOP_INDEX_2'] = "0"
var['LOOP_INDEX_3'] = "0"
var['LOOP_INDEX_4'] = "0"
var['LOOP_INDEX_5'] = "0"
var['LOOP_INDEX_6'] = "0"
var['LOOP_INDEX_7'] = "0"
var['LOOP_INDEX_8'] = "0"
var['LOOP_INDEX_9'] = "0"
target_groups = {}
marker = 'tilde'
loop_stack = []
null_loop_depth = 0

for in_file in input_files:
    f = open(in_file, 'r')
    filename = in_file
    lineno = '(yaml)'
    yd = yaml.load(f)
    f.close()

    # Attempt to auto-discover the variable marker ('$' or '~')
    f = open(in_file, 'r')
    data = f.read()
    f.close()
    dollar = data.count('${')
    tilde = data.count('~{')
    if dollar > 0 and tilde == 0:
        marker = 'dollar'
        _dbg('Setting variable marker to dollar ${}')
    elif dollar > 0 and tilde > 0:
        _wrn('Found both ${dollar} and ~{tilde} variable markers!')

    # Have to make sure we load all the vars, target-groups,
    # default-target, and set region/profile before
    # running the steps.
    if listing:
        _inf('File: %s' % filename)

    # Try up to 'maxtries' passes to resolve variable dependencies
    z = 0
    maxtries = 10
    vardep_keep_going = False
    while True:
        z += 1
        for k in yd.keys():
            lineno = '(%s...)' % str(k)[:10]
            if k == 'region':
                if not set_region(yd[k], z, maxtries):
                    vardep_keep_going = True
                else:
                    _dbg('region is set to %s' % region)
            elif k == 'profile':
                if not set_profile(yd[k], z, maxtries):
                    vardep_keep_going = True
                else:
                    _dbg('profile is set to %s' % profile)
            elif k[:4] == 'var.':
                if not set_var(k[4:], yd[k], z, maxtries):
                    vardep_keep_going = True
                else:
                    _dbg('var[%s] is set to %s' % (k[4:], var[k[4:]]))
            elif k == 'default-target':
                if not set_default_target(yd[k], z, maxtries):
                    vardep_keep_going = True
                else:
                    _dbg('default-target is set to %s' % target)
            elif k == 'target-groups':
                if not set_target_groups(yd[k], z, maxtries):
                    vardep_keep_going = True
        if (z >= maxtries) or (vardep_keep_going == False):
            break

    # List targets
    if listing:
        if default_found:
            _inf('Default target: %s' % target)
        else:
            _inf('Default target: (all steps)')
        for tgname in target_groups.keys():
            _inf('[%s]: %s' \
                % (tgname, ', '.join(target_groups[tgname])))
        for k in yd.keys():
            if k[:5] == 'steps':
                try:
                    tgt = varsub(k[6:])
                except ValueError as ex:
                    _err(str(ex))
                if tgt:
                    _inf(tgt)
                else:
                    if default_found:
                        _inf('(targetless - not reachable since ' \
                            + 'default target has been set)')
                    else:
                        _inf('(targetless)')
        continue

    # Make the targets in a target-group run in order
    if target and target in target_groups.keys():
        goals = target_groups[target]
    elif target:
        goals = [target]
    else:
        goals = [None]
    for goal in goals:
        for k in yd.keys():
            if k[:5] == 'steps':
                try:
                    tgt = varsub(k[6:])
                except ValueError as ex:
                    _err(str(ex))
                if goal and tgt != goal:
                    _dbg('Skipping %s (target: %s, goal: %s)' \
                         % (tgt, target, goal))
                    continue
                _dbg('Examining step list %s' % k)
                stepno = 0
                while stepno < len(yd[k]):
                    stepno += 1
                    step = yd[k][stepno - 1] # stepno is 1-based for printing
                    step_key = step.keys()[0]
                    lineno = '(%s)' % step_key
                    try:
                        rsrc_pathname = varsub(step_key)
                    except ValueError as ex:
                        _err(str(ex))
                    if rsrc_pathname == 'end-loop':
                        if len(loop_stack) == 0:
                            _err('Found "end-loop" outside of any loop.')
                        if end_null_loop():
                            continue
                        else:
                            if increment_loop_index():
                                stepno = loop_stack[-1][0]
                            continue
                    if rsrc_pathname == 'loop':
                        if check_null_loop():
                            add_null_loop()
                            continue
                        else:
                            start_loop(stepno, step[step_key])
                            continue
                    if check_null_loop():
                        _dbg('Inside a null loop. Skipping to the end.')
                        continue # If we're inside a null loop, skip to the end-loop
                    if rsrc_pathname == 'print':
                        if isinstance(step[step_key], basestring):
                            try:
                                print varsub(step[step_key])
                            except ValueError as ex:
                                _err(str(ex))
                        else:
                            _wrn('%s %s' \
                             % ('Print statements can only use string',
                                'arguments (with or without variables).'))
                        continue
                    if rsrc_pathname == 'clear-all-output':
                        if step[step_key]:
                            _inf('Running %s' % rsrc_pathname)
                            clear_all_output()
                        continue
                    if rsrc_pathname == 'clear-one-output':
                        if step[step_key]:
                            _inf('Running %s' % rsrc_pathname)
                            clear_one_output(varsub(step[step_key]))
                        continue
                    if rsrc_pathname == 'region':
                        set_region(step[step_key])
                        continue
                    if rsrc_pathname == 'profile':
                        set_profile(step[step_key])
                        continue
                    if rsrc_pathname[:4] == 'var.':
                        ky = rsrc_pathname[4:]
                        rawval = step[step_key]
                        set_var(ky, rawval)
                        continue
                    if os.path.exists('%s/%s' \
                                     % (outdir, rsrc_pathname)):
                        _dbg('%s has already been run.' % rsrc_pathname)
                        continue
                    if rsrc_pathname[0] == '+':
                        rsrc_pathname = rsrc_pathname[1:]
                    words = rsrc_pathname.split('.')
                    if words[0] == 'aws':
                        cmdtuple = (words[1], words[2])
                        argtupleraw = step[step_key]
                        _inf('Running %s' % rsrc_pathname)
                        outdict = aws_call(
                            region, profile, cmdtuple,
                            varsub_tuple(argtupleraw))
                        store_output(rsrc_pathname, outdict)
                    elif words[0] == 'exec':
                        cmd = words[1]
                        argtupleraw = step[step_key]
                        _inf('Running %s' % rsrc_pathname)
                        outdict = exec_call(
                            cmd, varsub_tuple(argtupleraw))
                        store_output(rsrc_pathname, outdict)
                    elif words[0] == 'ssh':
                        argtupleraw = step[step_key]
                        _inf('Running %s' % rsrc_pathname)
                        args = ['ssh']
                        args.extend(varsub_tuple(argtupleraw))
                        response = subprocess.call(args)
                    else:
                        _err('Unrecognized provider: %s' % words[0])

